### ISSUE TITLE
Why [<AbstractClass; Sealed>]  for constants ? 

### ISSUE THREAD

**Issue by evilz** [veepee-oss/Vp.FSharp.Sql.Sqlite#6]
https://github.com/veepee-oss/Vp.FSharp.Sql.Sqlite/blob/a35d89f3c588ee1f87b4d758a9bdf693f4ea5992/Vp.FSharp.Sql.Sqlite/Types.fs#L45-L46

Why not a module ?

**Comment by mary-perret-1986** [comment]
Cause under some specific circumstances (lib as dep + release conf), the initialization of a let binding (variable) in a module can be omitted by the compiler: see https://stackoverflow.com/questions/61937274/do-aggressive-f-compiler-optimizations-only-occur-on-referenced-dependencies

This doesn't occur with static classes.
